server:
   port: 8006

# 自定义的配置参数
myUploadPath: E:/上课资料/Cinema-line-website/C76-S3-YGL-clw-index/src/main/resources/static/sjkimage/ 
   
userlookPath: E:/上课资料/Cinema-line-website/C76-S3-YGL-clw-index/src/main/resources/static/userlook/

moviePath: E:/上课资料/Cinema-line-website/C76-S3-YGL-clw-index/src/main/resources/static/movieimg/

spring:
   application:
      name: clw-index
   datasource:
      url: jdbc:mysql://127.0.0.1/C76-S3-ygl-clw?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver
   resource: 
      staticLocations:  
         - classpath:/resources/
         - classpath:/static/
         - file:${myUploadPath}
   # 文件上传配置
   servlet: 
      multipart: 
         maxFileSize: 1000000000
         
   mail:
      # 邮箱服务器地址
      host: smtp.qq.com
      # 用户名
      username: 1481835274@qq.com
      # 密码 
      password: olivahgeqowmgead
      # 字符集编码
      default-encoding: UTF-8
      
# 以谁来发送邮件 自定义的参数
mail: 
   fromMail: 
      addr: 1481835274@qq.com

mybatis: 
  #实体类的路径
  type-aliases-package: com.yc.clw.bean
  configuration: 
     map-underscore-to-camel-case: true

#开启服务降级开关
feign:  
   hystrix: 
      enabled: true
   command:
    default:
      execution:
        timeout:
          isolation:
            thread:
              timeoutInMilliseconds: 30000
# 日志配置
logging:
  level:
    com:
      yc:
        clw:
          dao: debug
          web: warn
          
---
spring:  
   profiles: index-8007
server:  
   port: 8007
          
          
