spirng: 
   application: 
      name: clw-index
   
server:
   port: 80

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1/C76-S3-YGL-clw?serverTimezone=UTC&;CharacterEncoding=UTF-8&;useSSL=false
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #实体类的路径
  type-aliases-package: com.yc.clw.bean
  configuration:
     map-underscore-to-camel-case: true

#开启服务降级开关
feign: 
   hystrix: 
      enabled: true
  
# 日志配置
logging:
  level:
    com:
      yc:
        clw:
          dao: debug
          web: warn