server:
   port: 8006
   
   
spring:
  application:
     name: clw-index
  datasource:
     url: jdbc:mysql://127.0.0.1/C76-S3-ygl-clw?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver

mybatis: 
  #实体类的路径
  type-aliases-package: com.yc.clw.bean
  configuration: 
     map-underscore-to-camel-case: true

#开启服务降级开关
feign:  
   hystrix: 
      enabled: true
   command:
    default:
      execution:
        timeout:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
# 日志配置
logging:
  level:
    com:
      yc:
        clw:
          dao: debug
          web: warn
          
---
spring:  
   profiles: index-8007
server:  
   port: 8007
          
          
